[package]
name = "helix-rich-presence"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = { version = "6" }
discord-presence = { version = "1.5.0" }
thiserror = { version = "2" }
tokio = { version = "1", features = ["process", "macros", "time", "rt"] }
